CREATE DATABASE IF NOT EXISTS sf_aggregate;

CREATE TABLE sf_aggregate.host_metrics_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    collected_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    hostname VARCHAR(50),

    -- sfvispool fields
    pool_timestamp DATETIME,
    workstation TEXT,
    status TEXT,
    max_people INT,
    time_work TIME,

    -- sfOrinMonitoring fields
    orin_id INT,
    orin_time DATETIME,
    uptime VARCHAR(50),
    CPU1 INT,
    CPU2 INT,
    CPU3 INT,
    CPU4 INT,
    CPU5 INT,
    CPU6 INT,
    RAM FLOAT,
    SWAP INT,
    EMC INT,
    GPU INT,
    APE VARCHAR(10),
    NVDEC VARCHAR(10),
    NVJPG VARCHAR(10),
    NVJPG1 VARCHAR(10),
    OFA VARCHAR(10),
    SE VARCHAR(10),
    VIC VARCHAR(10),
    Fan_pwmfan0 FLOAT,
    Temp_CPU FLOAT,
    Temp_CV0 FLOAT,
    Temp_CV1 FLOAT,
    Temp_CV2 FLOAT,
    Temp_GPU FLOAT,
    Temp_SOC0 FLOAT,
    Temp_SOC1 FLOAT,
    Temp_SOC2 FLOAT,
    Temp_tj FLOAT,
    Power_CPU INT,
    Power_CV INT,
    Power_GPU INT,
    Power_SOC INT,
    Power_SYS5v INT,
    Power_VDDRQ INT,
    Power_tj INT,
    Power_TOT INT,
    jetson_clocks VARCHAR(10),
    nvp_model VARCHAR(50),
    disk_available_gb FLOAT,
    ip_address VARCHAR(50),
    model TEXT,
    jetpack TEXT,
    l4t TEXT,
    nv_power_mode TEXT,
    serial_number TEXT,
    p_number TEXT,
    module TEXT,
    distribution TEXT,
    release TEXT,
    cuda TEXT,
    cudnn TEXT,
    tensorrt TEXT,
    vpi TEXT,
    vulkan TEXT,
    opencv TEXT,

    INDEX idx_collected_at (collected_at)
);
